imports:
    - { resource: 'sources.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Infrastructure\UserData\Api\UserDataProvider:
        arguments:
            $sourceUrls: '%source_urls%'

    App\Infrastructure\UserData\Api\HttpClientFactory:
        arguments:
            $mockApi: '%mock_api%'
            $sourceStubs: '%source_stubs%'

    Symfony\Component\Serializer\NameConverter\NameConverterInterface:
        alias: 'serializer.name_converter.camel_case_to_snake_case'

    App\Application\UserProfile\PriorityResolver:
        arguments:
            $priority: '%source_weights%'
