parameters:
    source_priority:
        source1:
            email: 0
            name: 2
        source2:
            name: 0
        source3:
            name: 1
            avatar_url: 0
        source4:
            unknown: 0